### ISSUE TITLE
Is there any paper link or short notes about the V2? 

### ISSUE THREAD

**Issue by mmy12580** [IBM/Dromedary#11]
Just want to see the exact changes comparing to V1.

**Comment by Edward-Sun** [comment]
Hi Antoni,

In Appendix G IMPROVED PROMPT FOR SELF-ALIGN of our new SALMON paper:

https://arxiv.org/abs/2310.05910

We described what has changed compared to V1. Basically, we use the collected user prompts rather than self-instruct generated synthetic prompts and use an improved version of the SELF-ALIGN prompt.
