### ISSUE TITLE
evaluation code

### ISSUE THREAD

**Issue by Wangpeiyi9979** [IBM/Dromedary#9]
Hi, thanks for your excellent work.

Could you please share your evaluation code on truthful QA and BBH?

**Comment by Edward-Sun** [comment]
Hi Peiyi,

Thanks for waiting! We have just released the multichoice evaluation code [here](https://github.com/IBM/Dromedary/tree/main/mc_evaluation).

As for generation evaluation, we use the same inference code released [here](https://github.com/IBM/Dromedary/tree/main/inference).

We use the [standard prompt](https://github.com/IBM/Dromedary/blob/main/prompts/inference_prompts/dromedary_standard_prompt_distill.txt) for TruthfulQA generation evaluation, i.e.,

```
[standard_prompt]
### User
[TruthfulQA question]

### Dromedary
```

as described in our paper.

As for BBH, I don't think we reported any systematic evaluation in our paper. But since the inference code is provided, you can try some examples in with our ChatBot demo.
